services:
  - type: web
    name: iteratio2
    env: docker
    plan: starter
    region: frankfurt
    branch: main
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: iteratio2-db
          property: connectionString

databases:
  - name: iteratio2-db
    plan: starter
    region: frankfurt
    databaseName: iteratio2
    user: iteratio2 