"""Rename metadata to custom_data

Revision ID: 4562331bd4d1
Revises: 00df300402e2
Create Date: 2025-03-07 16:00:35.729392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4562331bd4d1'
down_revision = '00df300402e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultants', schema=None) as batch_op:
        batch_op.drop_column('custom_data')

    # ### end Alembic commands ###
