"""Add email and phone_number to Consultant model

Revision ID: e15250f54346
Revises: f0aab1235443
Create Date: 2025-03-06 14:07:59.483275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15250f54346'
down_revision = 'f0aab1235443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultants', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
